//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasMateria
    {
        public int Id { get; set; }
        public Nullable<double> Notas { get; set; }
        public int PersonaMateriaId { get; set; }
        public int Periodo_Id { get; set; }
    
        public  PersonaMateria PersonaMateria { get; set; }
        public  Periodo Periodo { get; set; }
    }
}
