//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaMateria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonaMateria()
        {
            this.NotasMateria = new HashSet<NotasMateria>();
        }
    
        public int Id { get; set; }
        public int Materia_Id { get; set; }
        public int Persona_Id { get; set; }
    
        public  Materia Materia { get; set; }
        public  Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<NotasMateria> NotasMateria { get; set; }
    }
}
